version: "3.3"

services:
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    expose:
      - "11211"
    networks:
      - internal_net

  game:
    build: .
    container_name: scoring-server
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.tls=true"
      - "traefik.http.routers.game.rule=Host(`game.ckf.gg`)"
      - "traefik.http.routers.game.entrypoints=websecure"
      - "traefik.http.routers.game.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik_traefik_net"
    volumes:
      - ./files:/opt/rtb/files:rw
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    depends_on:
      - memcached
    networks:
      - internal_net
      - traefik_traefik_net

networks:
  internal_net:
    internal: true
  traefik_traefik_net:
    external: true
